<?php
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/zipkinCore/zipkinCore_types.php';

$GLOBALS['zipkinCore_CONSTANTS'] = array();

$GLOBALS['zipkinCore_CONSTANTS']['CLIENT_SEND'] = "cs";

$GLOBALS['zipkinCore_CONSTANTS']['CLIENT_RECV'] = "cr";

$GLOBALS['zipkinCore_CONSTANTS']['SERVER_SEND'] = "ss";

$GLOBALS['zipkinCore_CONSTANTS']['SERVER_RECV'] = "sr";

?>
